"""remove image

Revision ID: 500f76e6e4dc
Revises: 1c53dc2c4a74
Create Date: 2025-02-24 07:51:02.610573

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "500f76e6e4dc"
down_revision = "1c53dc2c4a74"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "profile_image_url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "profile_image_url", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
