"""add token and blacklist

Revision ID: 5da2aa6b072e
Revises: e1f596b87391
Create Date: 2025-02-24 08:47:18.898635

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "5da2aa6b072e"
down_revision = "e1f596b87391"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tokenblacklist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tokenblacklist_token"), "tokenblacklist", ["token"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tokenblacklist_token"), table_name="tokenblacklist")
    op.drop_table("tokenblacklist")
    # ### end Alembic commands ###
