"""remove username

Revision ID: e1f596b87391
Revises: 500f76e6e4dc
Create Date: 2025-02-24 08:42:56.826575

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = "e1f596b87391"
down_revision = "500f76e6e4dc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "username", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
